version: "3"
services:
    rabbitmq:
        image: rabbitmq:3.8.5-management-alpine
        container_name: rabbit
        restart: always
        ports:
            - 15672:15672
            - 5672:5672

    pubs01:
        environment:             
             RabbitMq:Host: 192.168.0.11
             RabbitMq:Username: guest
             RabbitMq:Password: guest
        container_name: pubs01
        hostname: pubs01
        restart: always
        build:
            context: .
            dockerfile: src/MicroServices/Bari.Test.Publisher/Dockerfile
        depends_on:
        - rabbitmq
    pubs02:
        environment:           
            RabbitMq:Host: 192.168.0.11
            RabbitMq:Username: guest
            RabbitMq:Password: guest
        container_name: pubs02
        hostname: pubs02
        restart: always        
        build:
            context: .
            dockerfile: src/MicroServices/Bari.Test.Publisher/Dockerfile
        depends_on:
        - rabbitmq
    subs:
        environment:           
            RabbitMq:Host: 192.168.0.11
            RabbitMq:Username: guest
            RabbitMq:Password: guest
            container_name: subs01
            hostname: subs01
        restart: always
        build:
            context: .
            dockerfile: src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/Dockerfile
        depends_on:
        - rabbitmq