FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/Bari.Test.Services.Api.csproj", "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/"]
RUN dotnet restore "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/Bari.Test.Services.Api.csproj"
COPY . .
WORKDIR "/src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api"
RUN dotnet build "Bari.Test.Services.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "/Bari.Test.Services.Api/Bari.Test.Services.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Bari.Test.Services.Api.dll"]