#FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
#WORKDIR /app
#EXPOSE 80
#
#FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
#WORKDIR /src
#COPY ["Bari.Test.Services.Api.csproj", "src/Bari.Test.Services.Api/"]
#RUN dotnet restore "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/Bari.Test.Services.Api.csproj"
#COPY . .
#
#WORKDIR "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/"
#RUN dotnet build "Bari.Test.Services.Api.csproj" -c Release -o /app/build
#
#
#FROM build AS publish
#RUN dotnet publish "Bari.Test.Services.Api.csproj" -c Release -o /app/publish
#
#FROM base AS final
#WORKDIR /app
#COPY --from=publish /app/publish .
#ENTRYPOINT ["dotnet", "Bari.Test.Services.Api.dll"]
#
#
##

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore


# Copy everything else and build

RUN dotnet build -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Bari.Test.Services.Api.dll"]