#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/Bari.Test.Services.Api.csproj", "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/"]
COPY ["/src/MicroServices/Bari.Test.Subscriber/Bari.Test.Subscriber.Infra.IoC/Bari.Test.Subscriber.Infra.IoC.csproj", "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Subscriber.Infra.IoC/"]
COPY ["src/Domain/Bari.Test.Domain.Core/Bari.Test.Domain.Core.csproj", "src/Domain/Bari.Test.Domain.Core/"]
COPY ["src/MicroServices/Bari.Test.Subscriber/Bari.Test.Domain/Bari.Test.Domain.csproj", "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Domain/"]
RUN dotnet restore "src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api/Bari.Test.Services.Api.csproj"
COPY . .
WORKDIR "/src/src/MicroServices/Bari.Test.Subscriber/Bari.Test.Services.Api"
RUN dotnet build "Bari.Test.Services.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Bari.Test.Services.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Bari.Test.Services.Api.dll"]